//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityExercise
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHistory
    {
        public int UserHistoryId { get; set; }
        public string UserIP { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
        public Nullable<System.DateTime> LeaveTime { get; set; }
        public string Comment { get; set; }
    }
}
